/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as UsersRouteImport } from './routes/users'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryAuditRouteImport } from './routes/inventory.audit'
import { Route as InventoryExportRouteImport } from './routes/inventory.export'
import { Route as InventoryImportRouteImport } from './routes/inventory.import'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as OrdersCreateRouteImport } from './routes/orders.create'
import { Route as PosMinimalRouteImport } from './routes/pos.minimal'
import { Route as ShippingIndexRouteImport } from './routes/shipping.index'
import { Route as ShippingShippingIdRouteImport } from './routes/shipping.$shippingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAuditRoute = InventoryAuditRouteImport.update({
  id: '/inventory/audit',
  path: '/inventory/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryExportRoute = InventoryExportRouteImport.update({
  id: '/inventory/export',
  path: '/inventory/export',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryImportRoute = InventoryImportRouteImport.update({
  id: '/inventory/import',
  path: '/inventory/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCreateRoute = OrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PosMinimalRoute = PosMinimalRouteImport.update({
  id: '/minimal',
  path: '/minimal',
  getParentRoute: () => PosRoute,
} as any)
const ShippingIndexRoute = ShippingIndexRouteImport.update({
  id: '/shipping/',
  path: '/shipping/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingShippingIdRoute = ShippingShippingIdRouteImport.update({
  id: '/shipping/$shippingId',
  path: '/shipping/$shippingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/export': typeof InventoryExportRoute
  '/inventory/import': typeof InventoryImportRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
  '/pos/minimal': typeof PosMinimalRoute
  '/shipping/$shippingId': typeof ShippingShippingIdRoute
  '/books/': typeof BooksIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shipping/': typeof ShippingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/export': typeof InventoryExportRoute
  '/inventory/import': typeof InventoryImportRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
  '/pos/minimal': typeof PosMinimalRoute
  '/shipping/$shippingId': typeof ShippingShippingIdRoute
  '/books': typeof BooksIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/shipping': typeof ShippingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/export': typeof InventoryExportRoute
  '/inventory/import': typeof InventoryImportRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
  '/pos/minimal': typeof PosMinimalRoute
  '/shipping/$shippingId': typeof ShippingShippingIdRoute
  '/books/': typeof BooksIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shipping/': typeof ShippingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/assistant'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/pos'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/books/$bookId'
    | '/inventory/audit'
    | '/inventory/export'
    | '/inventory/import'
    | '/orders/$orderId'
    | '/orders/create'
    | '/pos/minimal'
    | '/shipping/$shippingId'
    | '/books/'
    | '/inventory/'
    | '/orders/'
    | '/shipping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/assistant'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/pos'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/books/$bookId'
    | '/inventory/audit'
    | '/inventory/export'
    | '/inventory/import'
    | '/orders/$orderId'
    | '/orders/create'
    | '/pos/minimal'
    | '/shipping/$shippingId'
    | '/books'
    | '/inventory'
    | '/orders'
    | '/shipping'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/analytics'
    | '/assistant'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/login'
    | '/pos'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/books/$bookId'
    | '/inventory/audit'
    | '/inventory/export'
    | '/inventory/import'
    | '/orders/$orderId'
    | '/orders/create'
    | '/pos/minimal'
    | '/shipping/$shippingId'
    | '/books/'
    | '/inventory/'
    | '/orders/'
    | '/shipping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  UsersRoute: typeof UsersRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  InventoryAuditRoute: typeof InventoryAuditRoute
  InventoryExportRoute: typeof InventoryExportRoute
  InventoryImportRoute: typeof InventoryImportRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersCreateRoute: typeof OrdersCreateRoute
  ShippingShippingIdRoute: typeof ShippingShippingIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ShippingIndexRoute: typeof ShippingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/audit': {
      id: '/inventory/audit'
      path: '/inventory/audit'
      fullPath: '/inventory/audit'
      preLoaderRoute: typeof InventoryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/export': {
      id: '/inventory/export'
      path: '/inventory/export'
      fullPath: '/inventory/export'
      preLoaderRoute: typeof InventoryExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/import': {
      id: '/inventory/import'
      path: '/inventory/import'
      fullPath: '/inventory/import'
      preLoaderRoute: typeof InventoryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/create': {
      id: '/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof OrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/minimal': {
      id: '/pos/minimal'
      path: '/minimal'
      fullPath: '/pos/minimal'
      preLoaderRoute: typeof PosMinimalRouteImport
      parentRoute: typeof PosRoute
    }
    '/shipping/': {
      id: '/shipping/'
      path: '/shipping'
      fullPath: '/shipping/'
      preLoaderRoute: typeof ShippingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping/$shippingId': {
      id: '/shipping/$shippingId'
      path: '/shipping/$shippingId'
      fullPath: '/shipping/$shippingId'
      preLoaderRoute: typeof ShippingShippingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PosRouteChildren {
  PosMinimalRoute: typeof PosMinimalRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosMinimalRoute: PosMinimalRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRouteWithChildren,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  UsersRoute: UsersRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  InventoryAuditRoute: InventoryAuditRoute,
  InventoryExportRoute: InventoryExportRoute,
  InventoryImportRoute: InventoryImportRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersCreateRoute: OrdersCreateRoute,
  ShippingShippingIdRoute: ShippingShippingIdRoute,
  BooksIndexRoute: BooksIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ShippingIndexRoute: ShippingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
